language: android

sudo: false
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    #- sys-img-armeabi-v7a-android-19

os:
  - linux

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug -xlint

env:
  - secure: "n0aUjx4h2ILGdSae6y7kq+WbIw95aEIpovy/ZVmB8Du/S5sCRw0b4UFr9Mhp98gLhejNblOtx5EeZ5K1wdyTrJQtztbFu2gNSC5k0EYdVH15c+mZewyGcBmfIXAP8flfrF1MR8+ekeNPYaYd/kG6itP0XSXiE2B1qv5qRNmvL4+FLQ+kS90E0DT5NmZLjVzJVaHcdQZ9FQqy1MtNHrgKtXpRmzDo4YYa33HAQjIIQ7uuceQFv4H+2pzBMpsYFLnQZA5dPyxzUCze5En55ApJN1vVW3+BxkTDLFzdhQy81jpcYFhkxlPVAe8GhyyJoxyIM4M185fj4hcbRRVan0lDuIYdLT0fkPbWigNYWDkkVhLGQZvttSbfs60ixmDjpBfc1m2nh28KmbPScwGKnGzqmugk9Cjfiilko9h99uatoSiQQvvQMhtcU4WmuL4gp1iO5GSKguZNl7oIKBFqL5AetF0Oyx+zu4isPpD+R8/iUkd9o8qPmj/+kKBMM6DYAVmfa/Ih6foGhx5igwGWdeaG3UNdlY7ymdVmyhb77GH8MkqiBbVdkovAcHcQMKwKZRlYT2NuVwRSHSfwKWHEU/TAAeId4SuY4Kvbe8xrJnvSdpiMtx/x4lyTOo2xfEOK2MfAnyieCxe3VFdKWOxEEi+zRA0GfpC0wX2uBU85ZQhmk/4="